Bookstore: styling
codedit334/Bookstore_ReactJS pull request #5
Opened 2023-04-05 17:41 UTC by codedit334

## Hi Reviewer 👋,

In this PR:
- Added SX elements to your project for missing parts.
- Final design matches Zeplin's design.
- Used the CSS rules detailed in Zeplin to style the website.

# 🤝

2023-04-05 18:08 UTC, huseyinbiyik requested changes
Hi @codedit334 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Git flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
<img width="1440" alt="Screenshot 2023-04-05 at 9 01 39 PM" src="https://user-images.githubusercontent.com/25887253/230165920-547348da-1db1-4060-998f-b81755543369.png">

You did a great job adding your design taste to this project. But unfortunately, we expect you to code the Zeplin design **exactly** the same. 
<img width="720" alt="Screenshot 2023-04-05 at 8 48 24 PM" src="https://user-images.githubusercontent.com/25887253/230164226-30ac72cc-25ab-4c6b-bf20-ffde63196665.png"> Since Zeplin gives you all the CSS values, all you need to do is to implement the design with  [HTML&CSS Best Practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):  , considering the rules below.
No repeating of the same rule
No ID selectors for multiple elements
No !important overusing
No inefficient selectors
No inline styling
<img width="1160" alt="Screenshot 2023-04-05 at 8 57 40 PM" src="https://user-images.githubusercontent.com/25887253/230164881-05df7f61-f739-44e4-92ae-777131f13829.png">

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML" 

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 18:08 UTC, huseyinbiyik commented on src/components/Book.js
> +          {/* <span className="book-space">Title:</span> */}
Please don't leave any uncommented code in your all codebase. In this way, you can keep your codebase clean, organized, and professional. If you need a specific line of code, you can use git checkout `
<commitnumber>`  .

2023-04-05 18:20 UTC, codedit334 commented
Hi @huseyinbiyik, Thank you for taking the time to review my work,
I made sure the overall layout is similar to the one on Zeplin...
By 'Match the Zeplin design' do You mean similar colors or similar CSS values?

2023-04-05 19:04 UTC, huseyinbiyik commented
Hey @codedit334 , This time, it needs to be exactly the same as Zeplin's design. Not the best example but please check this [one](https://deploy-preview-5--shimmering-kangaroo-bc7705.netlify.app/Books).

2023-04-05 20:17 UTC, codedit334 commented
Thank you @huseyinbiyik

2023-04-06 16:43 UTC, huseyinbiyik approved these changes
Hi @codedit334 again,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- The design looks identical. 👌 
- Linter set up well and checks pass 🟢
- Git flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝
- Great implementation of the requested changes 🕸️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 16:45 UTC, merged